### ISSUE TITLE
Crash when reading JSON file

### ISSUE THREAD

**Issue by achingbrain** [hugomrdias/playwright-test#293]
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getPw (file:///home/travis/build/ipfs/js-ipfs/node_modules/playwright-test/src/utils/index.js:261:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MochaRunner.launch (file:///home/travis/build/ipfs/js-ipfs/node_modules/playwright-test/src/runner.js:109:16)
    at async MochaRunner.run (file:///home/travis/build/ipfs/js-ipfs/node_modules/playwright-test/src/runner.js:265:23)
Command failed with exit code 1: pw-test **/*.spec.{js,ts} test/browser.{js,ts} --mode main --config /home/travis/build/ipfs/js-ipfs/node_modules/aegir/src/config/pw-test.js --timeout=60000 --bail
```

**Comment by hugomrdias** [comment]
can i get more info on this? i can't repro
