### ISSUE TITLE
Intermittent failure during test setup

### ISSUE THREAD

**Issue by achingbrain** [hugomrdias/playwright-test#410]
**Describe the bug**

Sometimes running tests with playwright-test fails with a 404 before the test run starts.  Doesn't happen every time, there could be a race condition somewhere.

**To Reproduce**

Run some tests:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:58129/setup.js
✖ Running tests failed.
page.addScriptTag: Error: Failed to load script at http://127.0.0.1:58129/setup.js
    at HTMLScriptElement.script.onerror (eval at evaluate (:3:2389), <anonymous>:8:74)
    at MochaRunner.runTests (file:///path/to/project/node_modules/playwright-test/src/runner.js:231:16)
    at MochaRunner.runTests (file:///path/to/project/node_modules/playwright-test/src/runner-mocha.js:53:44)
    at MochaRunner.run (file:///path/to/project/node_modules/playwright-test/src/runner.js:287:38)
Command failed with exit code 1: pw-test **/*.spec.{js,ts,cjs,mjs} test/browser.{js,ts,cjs,mjs} --mode main --cov --config /path/to/project/node_modules/aegir/src/config/pw-test.js --timeout=60000
```

**Expected behavior**

The test suite to start

**Desktop (please complete the following information):**

Happens on Mac OS X and Linux on CI

**Comment by hugomrdias** [comment]
seems the static http server is not ready in time for the pw run, weird...
 
```bash
pw-test **/*.spec.{js,ts,cjs,mjs} test/browser.{js,ts,cjs,mjs} --mode main --cov --config /path/to/project/node_modules/aegir/src/config/pw-test.js --timeout=60000
```

can you copy paste the config here please?

**Comment by achingbrain** [comment]
```console
% cat /path/to/project/node_modules/aegir/src/config/pw-test.js
import { loadUserConfig } from './user.js'

export default async () => {
  const userConfig = await loadUserConfig()

  return userConfig.test.browser.config || {}
}
```

```console
% cat /path/to/project/node_modules/aegir/src/config/user.js   
/* eslint-disable no-console */

import { lilconfig } from 'lilconfig'
import merge from 'merge-options'
import { pathToFileURL } from 'url'

/**
 * @typedef {import("./../types").Options} Options
 */

/** @type {Omit<Options, "fileConfig">} */
const defaults = {
  // global options
  debug: false,
  // test cmd options
  test: {
    build: false,
    runner: 'node',
    target: ['node', 'browser', 'webworker'],
    watch: false,
    files: [],
    timeout: 60000,
    grep: '',
    bail: false,
    progress: false,
    cov: false,
    browser: {
      config: {
        buildConfig: {
          conditions: ['production']
        }
      }
    },
    before: async () => { return undefined },
    after: async () => {}
  },
  // build cmd options
  build: {
    bundle: true,
    bundlesize: false,
    bundlesizeMax: '100kB',
    types: true,
    config: {}
  },
  // linter cmd options
  lint: {
    silent: false,
    fix: false,
    files: [
      '*.{js,ts}',
      'bin/**',
      'config/**/*.{js,ts}',
      'test/**/*.{js,ts}',
      'src/**/*.{js,ts}',
      'tasks/**/*.{js,ts}',
      'benchmarks/**/*.{js,ts}',
      'utils/**/*.{js,ts}',
      '!**/node_modules/**'
    ]
  },
  // docs cmd options
  docs: {
    publish: false,
    entryPoint: 'src/index.js'
  },
  // ts cmd options
  ts: {
    preset: undefined,
    include: []
  },
  // release cmd options
  release: {
    build: true,
    types: true,
    test: true,
    lint: true,
    contributors: true,
    bump: true,
    changelog: true,
    publish: true,
    commit: true,
    tag: true,
    push: true,
    ghrelease: true,
    docs: true,
    ghtoken: '',
    type: 'patch',
    preid: undefined,
    distTag: 'latest',
    remote: 'origin'
  },
  // dependency check cmd options
  dependencyCheck: {
    input: [
      'package.json',
      '.aegir.js',
      '.aegir.cjs',
      'src/**/*.js',
      'src/**/*.cjs',
      'test/**/*.js',
      'test/**/*.cjs',
      'dist/**/*.js',
      'benchmarks/**/*.js',
      'benchmarks/**/*.cjs',
      'utils/**/*.js',
      'utils/**/*.cjs',
      '!./test/fixtures/**/*.js',
      '!./test/fixtures/**/*.cjs'
    ],
    productionOnly: false,
    productionInput: [
      'package.json',
      'src/**/*.js',
      'src/**/*.cjs',
      'dist/src/**/*.js',
      'utils/**/*.js',
      'utils/**/*.cjs'
    ],
    ignore: [
      '@types/*'
    ]
  }
}

/**
 * Search for local user config
 *
 * @param {string | undefined} [searchFrom]
 * @returns {Promise<Options>}
 */
export const config = async (searchFrom) => {
  let userConfig
  try {
    const loadEsm = async (/** @type {string} */ filepath) => {
      /** @type {any} */
      const res = await import(pathToFileURL(filepath).toString())

      if (res.default != null) {
        return res.default
      }

      if (typeof res.toString === 'function') {
        return res
      }

      // if there's no toString function, this was an ES module that didn't export anything
      return {}
    }
    const loadedConfig = await lilconfig('aegir', {
      loaders: {
        '.js': loadEsm,
        '.mjs': loadEsm
      },
      searchPlaces: [
        'package.json',
        '.aegir.js',
        '.aegir.cjs'
      ]
    })
      .search(searchFrom)

    if (loadedConfig) {
      userConfig = loadedConfig.config
    } else {
      userConfig = {}
    }
  } catch (err) {
    console.error(err)
    throw new Error('Error finding your config file.')
  }

  const conf = /** @type {Options} */(merge(
    defaults,
    userConfig
  ))

  return conf
}

export const loadUserConfig = () => config()
```

**Comment by hugomrdias** [comment]
@achingbrain can you test 7.4.1 to see if it makes a difference please?

**Comment by achingbrain** [comment]
It's really hard to replicate, I guess if I don't see the error again in the next month it's fixed?

**Comment by hugomrdias** [comment]
@achingbrain any problems since last time ?

**Comment by achingbrain** [comment]
So far so good. This may be safe to close.

**Comment by achingbrain** [comment]
I'm seeing this again:

- https://github.com/ipfs/helia-unixfs/actions/runs/6185702744/job/16791920448
- https://github.com/ipfs/helia-unixfs/actions/runs/6185702744/job/16791919843

**Comment by achingbrain** [comment]
Actually never mind, I think it's a problem with esbuild.
