### ISSUE TITLE
Error: ReferenceError: mocha is not defined

### ISSUE THREAD

**Issue by Gozala** [hugomrdias/playwright-test#52]
As I was working on https://github.com/achingbrain/it/issues/8 I started seeing following errors coming from playwright-test

```
npm test
> browser-readablestream-to-it@0.0.1 test /Users/gozala/Projects/it/packages/browser-readablestream-to-it
> playwright-test

✔ Browser setup
✔ Bundling tests
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
file:////Users/gozala/Projects/it/node_modules/mocha/mocha.js:25915

 Error: ReferenceError: mocha is not defined
    at eval (file:////Users/gozala/Projects/it/node_modules/playwright-test/src/setup-mocha.js:9:1)
    at Object.../../node_modules/playwright-test/src/setup-mocha.js (http://localhost:3000/bundle.509459cbd52e64d9231b.js:519:1)
    at __webpack_require__ (http://localhost:3000/bundle.509459cbd52e64d9231b.js:20:30)
    at eval (file:///multi%2520/Users/gozala/Projects/it/node_modules/playwright-test/src/setup-mocha.js%2520/Users/gozala/Projects/it/packages/browser-readablestream-to-it/test.js:1:1)
    at Object.0 (http://localhost:3000/bundle.509459cbd52e64d9231b.js:588:1)
    at __webpack_require__ (http://localhost:3000/bundle.509459cbd52e64d9231b.js:20:30)
    at http://localhost:3000/bundle.509459cbd52e64d9231b.js:84:18
    at http://localhost:3000/bundle.509459cbd52e64d9231b.js:87:10
npm ERR! Test failed.  See above for more details.
```

To check if there was something wrong with my changes or setup I submitted pull with muster and empty commit here 
https://github.com/achingbrain/it/pull/10

Which seems to still fail https://travis-ci.org/github/achingbrain/it/jobs/715667645

Not sure what is causing this yet.

**Comment by Gozala** [comment]
Master that was publish 13 days ago seems to have passed all these test https://github.com/achingbrain/it/commit/1b928cb642765eeac0264817b34b2482e30e0df5

**Comment by Gozala** [comment]
I'm guessing some of the minor deps got published causing this.

**Comment by Gozala** [comment]
```
npm ls mocha --dev            
browser-readablestream-to-it@0.0.1 /Users/gozala/Projects/it/packages/browser-readablestream-to-it
└── UNMET DEPENDENCY mocha@^8.0.1

npm ERR! missing: mocha@^8.0.1, required by browser-readablestream-to-it@0.0.1
```

Not sure why, but I'm starting to think this might be problem with `it` instead.

**Comment by Gozala** [comment]
Ok looks like issue has to do with the fact that despite `"mocha": "^8.0.1"` in `package.json` version installed ends up been `mocha@8.1.1` which seems to cause trouble. Setting version to strict `"mocha": "8.0.1"` seems to resolve the problem. However that also suggest that playwright-test is incompatible with `mocha@8.1.1`.
