### ISSUE TITLE
Fails to resolve the test runner module

### ISSUE THREAD

**Issue by Gozala** [hugomrdias/playwright-test#561]
**Describe the bug**

I was updating libraries that used https://github.com/hugomrdias/playwright-test/pull/548 to currently released playwright, but sadly it seems to fail to resolve the module

```
playwright-test test --runner entail test/*.js

Error: Cannot resolve module "entail" from "/Users/gozala/Projects/entail"
    at resolveModule (file:///Users/gozala/Projects/entail/node_modules/.pnpm/playwright-test@11.0.2/node_modules/playwright-test/src/utils/index.js:524:11)
    at async resolveTestRunner (file:///Users/gozala/Projects/entail/node_modules/.pnpm/playwright-test@11.0.2/node_modules/playwright-test/src/utils/index.js:544:18)
    at async file:///Users/gozala/Projects/entail/node_modules/.pnpm/playwright-test@11.0.2/node_modules/playwright-test/cli.js:273:34
 ELIFECYCLE  Command failed with exit code 1.
```

**To Reproduce**

Execute above command

**Expected behavior**

I was expecting that module resolution would succeed

**Additional context**

I am not yet sure why that error is happening, but I suspect that module resolution logic provided in my PR and one that was shipped are different, later failing to account for the context in which resolution takes place.

I will investigate and provide more details as I find them.

**Comment by Gozala** [comment]
Ok taking a closer look I can tell the problem is indeed with module resolution logic, specifically this code is not going to take into account package within which resolution occurs, that is to say if my package has dependency `entail` specifying `--runner entail` will not work, I would need to path a path to it like `./node_modules/entail/src/lib.js` which is not ideal because depending on the package manager, monorepo setup etc.. path may end up different

https://github.com/hugomrdias/playwright-test/blob/2d1c32deef36a80a1cf2bff13cc0617b477a6a9c/src/utils/index.js#L509-L528


Module resolution logic in proposed PR instead used nodes `module` module in order to perform resolution from the context of the working directory, which meant that if I have a dependency with specific name I could pass it in the `--runner` options regardless of package manager, monoreponess etc...

https://github.com/Gozala/playwright-test/blob/523e0c3d9e2d72f8f1ec8ae05c830ddc8cfa6aa3/src/utils/index.js#L468-L483
