### ISSUE TITLE
Version 11 no longer runs test files with typescript syntax unless you manually specify the test runner

### ISSUE THREAD

**Issue by birtles** [hugomrdias/playwright-test#565]
**Describe the bug**
After updating from v10.0.1 to v11.0.3 (or just v11.0.0) I can no longer run typescript test files that have any typescript syntax.

**To Reproduce**

1. Create a test file with typescript syntax (e.g. type annotations)
2. Run `npx playwright-test example.test.ts`

**Expected behavior**
The test runs.

**Actual behavior**
`acorn` trips up on the typescript syntax, e.g.

```
❯ yarn playwright-test src/update.test.ts
yarn run v1.22.19
warning package.json: No license field
$ /home/birtles/jpdict-idb/node_modules/.bin/playwright-test src/update.test.ts
SyntaxError: Unexpected token (61:27)
    at pp$4.raise (file:///home/birtles/jpdict-idb/node_modules/acorn/dist/acorn.mjs:3554:13)
    at pp$9.unexpected (file:///home/birtles/jpdict-idb/node_modules/acorn/dist/acorn.mjs:762:8)
    at pp$8.parseVar (file:///home/birtles/jpdict-idb/node_modules/acorn/dist/acorn.mjs:1313:12)
    at pp$8.parseVarStatement (file:///home/birtles/jpdict-idb/node_modules/acorn/dist/acorn.mjs:1175:8)
    at pp$8.parseStatement (file:///home/birtles/jpdict-idb/node_modules/acorn/dist/acorn.mjs:917:17)
    at pp$8.parseTopLevel (file:///home/birtles/jpdict-idb/node_modules/acorn/dist/acorn.mjs:819:21)
    at Parser.parse (file:///home/birtles/jpdict-idb/node_modules/acorn/dist/acorn.mjs:591:15)
    at Function.parse (file:///home/birtles/jpdict-idb/node_modules/acorn/dist/acorn.mjs:641:35)
    at parse (file:///home/birtles/jpdict-idb/node_modules/acorn/dist/acorn.mjs:5943:17)
    at detectTestRunner (file:///home/birtles/jpdict-idb/node_modules/playwright-test/src/utils/auto-detect.js:11:22) {
  pos: 1203,
  loc: Position { line: 61, column: 27 },
  raisedAt: 1204
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Ubuntu 22.04.2
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] ? (Not sure what this is asking for. OS version? Browser version?)

**Additional context**
If I have a `.ts` file that doesn't happen to use any type annotations etc. it works fine. The position of the error seems to correspond to the first bit of syntax that is not javascript, (e.g. a type annotation).

From what I can tell, it looks like this is due to the test runner auto-detection code. Part of this was added in 10.0.1 (477ec995b26075389f61ba1d1d04d1d6d5ec2ede) but it wasn't actually _used_ until 11.0.0 (1d73a36723048c850eb387f41b20d33c4e559826).

If I specify the test runner explicitly (e.g. `-r mocha`) it works.

It appears the auto-detection code is attempting to parse the test file using `acorn` which doesn't support parsing typescript (see https://github.com/acornjs/acorn/issues/1162#issuecomment-1334544532).

It has [been suggested elsewhere to use typescript-estree](https://github.com/acornjs/acorn/issues/1162#issuecomment-1405243042) to parse typescript files. (Although the link in that comment is broken, an updated link to typescript-estree is: https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/typescript-estree.)

**Comment by hugomrdias** [comment]
i will take a look thank you

**Comment by hugomrdias** [comment]
can you please check 11.0.4 ?

**Comment by birtles** [comment]
Yes, that works. Thank you!
